// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: asd.sql

package tutorial

import (
	"context"
)

const asd = `-- name: asd :one
select 1
`

func (q *Queries) asd(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, asd)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const foo = `-- name: foo :exec
select 1
`

func (q *Queries) foo(ctx context.Context) error {
	_, err := q.db.Exec(ctx, foo)
	return err
}
